task_name: "crc"
gpu_id: 0
log_dir: "./logs/task005"
tensorboard:
  enabled: true
  log_dir: "./logs/task005/tensorboard"  # TensorBoard 日志文件保存路径

save_frequency: 10000 # 每 n 个 epoch 保存一次模型
save_dir: "./checkpoints/task005"  # 模型保存路径
best_metric_name: "auc_score"

sequence: "CT"
batch_size: 32
epochs: 1000
validation_frequency: 1

train_dataset_dir: "datasets/raw/CRC_roi"
val_dataset_dir: "datasets/raw/CRC_roi"
test_dataset_dir: "datasets/raw/CRC_roi"

#model: "models.task002_resnet3D.ResNet3D"               # 模型路径
model: "models.task005_vit.Vit3D"
dataset: "datasets.task005_dataset.Task005Dataset"       # 数据集路径
dataloader: "data.dataloaders.base_dataloader.BaseDataLoader"  # 数据加载器路径

loss_function: "torch.nn.CrossEntropyLoss"           # 损失函数路径
optimizer:                                           # 优化器配置
  type: "torch.optim.Adam"                           # 优化器路径
  params:                                            # 优化器参数
    lr: 0.001

#scheduler:                                           # 学习率衰减策略配置
#  type: "torch.optim.lr_scheduler.StepLR"            # 学习率衰减策略路径
#  params:                                            # 学习率衰减策略参数
#    step_size: 50
#    gamma: 0.1

# 数据预处理配置
preprocessing:
  train_transform: "data.transforms.train_transform.train_transform"  # 训练集数据预处理
  val_transform: "data.transforms.val_transform.val_transform"      # 验证集数据预处理

# 验证指标配置
metrics:
    - "modules.metrics.accuracy.accuracy"
    - "modules.metrics.f1_score.f1_score"
    - "modules.metrics.precision_recall.precision"
    - "modules.metrics.precision_recall.recall"
    - "modules.metrics.auc.auc_score"

# 评估函数
evaluation:
  function: "modules.evaluation.final_evaluate"  # 评估函数路径
  evaluation_metrics:
    - "modules.metrics.accuracy.accuracy"
    - "modules.metrics.f1_score.f1_score"
    - "modules.metrics.precision_recall.precision"
    - "modules.metrics.precision_recall.recall"
    - "modules.metrics.auc.auc_score"
  save_visuals: true  # 是否保存可视化文件（如 ROC 曲线）
  visuals_dir: "./visuals/task005"  # 可视化文件保存路径